// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/AlarmInfo.proto

package protocol;

public final class AlarmInfoProtos {
  private AlarmInfoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AlarmInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.AlarmInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string Id = 1;</code>
     *
     * <pre>
     *报警标号
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required string Id = 1;</code>
     *
     * <pre>
     *报警标号
     * </pre>
     */
    String getId();
    /**
     * <code>required string Id = 1;</code>
     *
     * <pre>
     *报警标号
     * </pre>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required string VehicleId = 2;</code>
     *
     * <pre>
     *车辆信息编号
     * </pre>
     */
    boolean hasVehicleId();
    /**
     * <code>required string VehicleId = 2;</code>
     *
     * <pre>
     *车辆信息编号
     * </pre>
     */
    String getVehicleId();
    /**
     * <code>required string VehicleId = 2;</code>
     *
     * <pre>
     *车辆信息编号
     * </pre>
     */
    com.google.protobuf.ByteString
        getVehicleIdBytes();

    /**
     * <code>required string PreyInfoId = 3;</code>
     *
     * <pre>
     * 布控信息编号
     * </pre>
     */
    boolean hasPreyInfoId();
    /**
     * <code>required string PreyInfoId = 3;</code>
     *
     * <pre>
     * 布控信息编号
     * </pre>
     */
    String getPreyInfoId();
    /**
     * <code>required string PreyInfoId = 3;</code>
     *
     * <pre>
     * 布控信息编号
     * </pre>
     */
    com.google.protobuf.ByteString
        getPreyInfoIdBytes();

    /**
     * <code>required uint32 Priority = 4;</code>
     *
     * <pre>
     *报警级别　同于布控级别
     * </pre>
     */
    boolean hasPriority();
    /**
     * <code>required uint32 Priority = 4;</code>
     *
     * <pre>
     *报警级别　同于布控级别
     * </pre>
     */
    int getPriority();

    /**
     * <code>required string DeviceId = 5;</code>
     */
    boolean hasDeviceId();
    /**
     * <code>required string DeviceId = 5;</code>
     */
    String getDeviceId();
    /**
     * <code>required string DeviceId = 5;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <code>required string Time = 6;</code>
     */
    boolean hasTime();
    /**
     * <code>required string Time = 6;</code>
     */
    String getTime();
    /**
     * <code>required string Time = 6;</code>
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    /**
     * <code>required uint32 Type = 7;</code>
     *
     * <pre>
     *报警类型　同于布控类型
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required uint32 Type = 7;</code>
     *
     * <pre>
     *报警类型　同于布控类型
     * </pre>
     */
    int getType();

    /**
     * <code>optional string PlateLicense = 8;</code>
     */
    boolean hasPlateLicense();
    /**
     * <code>optional string PlateLicense = 8;</code>
     */
    String getPlateLicense();
    /**
     * <code>optional string PlateLicense = 8;</code>
     */
    com.google.protobuf.ByteString
        getPlateLicenseBytes();

    /**
     * <code>optional string PlateColor = 9;</code>
     */
    boolean hasPlateColor();
    /**
     * <code>optional string PlateColor = 9;</code>
     */
    String getPlateColor();
    /**
     * <code>optional string PlateColor = 9;</code>
     */
    com.google.protobuf.ByteString
        getPlateColorBytes();

    /**
     * <code>optional string PlateType = 10;</code>
     */
    boolean hasPlateType();
    /**
     * <code>optional string PlateType = 10;</code>
     */
    String getPlateType();
    /**
     * <code>optional string PlateType = 10;</code>
     */
    com.google.protobuf.ByteString
        getPlateTypeBytes();

    /**
     * <code>optional string VehicleLogoRecog = 11;</code>
     */
    boolean hasVehicleLogoRecog();
    /**
     * <code>optional string VehicleLogoRecog = 11;</code>
     */
    String getVehicleLogoRecog();
    /**
     * <code>optional string VehicleLogoRecog = 11;</code>
     */
    com.google.protobuf.ByteString
        getVehicleLogoRecogBytes();

    /**
     * <code>optional string VehicleColor = 12;</code>
     */
    boolean hasVehicleColor();
    /**
     * <code>optional string VehicleColor = 12;</code>
     */
    String getVehicleColor();
    /**
     * <code>optional string VehicleColor = 12;</code>
     */
    com.google.protobuf.ByteString
        getVehicleColorBytes();

    /**
     * <code>optional int32 VehicleType = 13;</code>
     */
    boolean hasVehicleType();
    /**
     * <code>optional int32 VehicleType = 13;</code>
     */
    int getVehicleType();

    /**
     * <code>optional float VehicleSpeed = 14;</code>
     */
    boolean hasVehicleSpeed();
    /**
     * <code>optional float VehicleSpeed = 14;</code>
     */
    float getVehicleSpeed();
  }
  /**
   * Protobuf type {@code protocol.AlarmInfo}
   */
  public static final class AlarmInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protocol.AlarmInfo)
      AlarmInfoOrBuilder {
    // Use AlarmInfo.newBuilder() to construct.
    private AlarmInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AlarmInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AlarmInfo defaultInstance;
    public static AlarmInfo getDefaultInstance() {
      return defaultInstance;
    }

    public AlarmInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AlarmInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              vehicleId_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              preyInfoId_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              priority_ = input.readUInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              deviceId_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              time_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              type_ = input.readUInt32();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              plateLicense_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              plateColor_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              plateType_ = bs;
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              vehicleLogoRecog_ = bs;
              break;
            }
            case 98: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000800;
              vehicleColor_ = bs;
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              vehicleType_ = input.readInt32();
              break;
            }
            case 117: {
              bitField0_ |= 0x00002000;
              vehicleSpeed_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AlarmInfoProtos.internal_static_protocol_AlarmInfo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AlarmInfoProtos.internal_static_protocol_AlarmInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AlarmInfo.class, Builder.class);
    }

    public static com.google.protobuf.Parser<AlarmInfo> PARSER =
        new com.google.protobuf.AbstractParser<AlarmInfo>() {
      public AlarmInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AlarmInfo(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<AlarmInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private Object id_;
    /**
     * <code>required string Id = 1;</code>
     *
     * <pre>
     *报警标号
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string Id = 1;</code>
     *
     * <pre>
     *报警标号
     * </pre>
     */
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Id = 1;</code>
     *
     * <pre>
     *报警标号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VEHICLEID_FIELD_NUMBER = 2;
    private Object vehicleId_;
    /**
     * <code>required string VehicleId = 2;</code>
     *
     * <pre>
     *车辆信息编号
     * </pre>
     */
    public boolean hasVehicleId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string VehicleId = 2;</code>
     *
     * <pre>
     *车辆信息编号
     * </pre>
     */
    public String getVehicleId() {
      Object ref = vehicleId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          vehicleId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string VehicleId = 2;</code>
     *
     * <pre>
     *车辆信息编号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getVehicleIdBytes() {
      Object ref = vehicleId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        vehicleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PREYINFOID_FIELD_NUMBER = 3;
    private Object preyInfoId_;
    /**
     * <code>required string PreyInfoId = 3;</code>
     *
     * <pre>
     * 布控信息编号
     * </pre>
     */
    public boolean hasPreyInfoId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string PreyInfoId = 3;</code>
     *
     * <pre>
     * 布控信息编号
     * </pre>
     */
    public String getPreyInfoId() {
      Object ref = preyInfoId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          preyInfoId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string PreyInfoId = 3;</code>
     *
     * <pre>
     * 布控信息编号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPreyInfoIdBytes() {
      Object ref = preyInfoId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        preyInfoId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRIORITY_FIELD_NUMBER = 4;
    private int priority_;
    /**
     * <code>required uint32 Priority = 4;</code>
     *
     * <pre>
     *报警级别　同于布控级别
     * </pre>
     */
    public boolean hasPriority() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint32 Priority = 4;</code>
     *
     * <pre>
     *报警级别　同于布控级别
     * </pre>
     */
    public int getPriority() {
      return priority_;
    }

    public static final int DEVICEID_FIELD_NUMBER = 5;
    private Object deviceId_;
    /**
     * <code>required string DeviceId = 5;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string DeviceId = 5;</code>
     */
    public String getDeviceId() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string DeviceId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 6;
    private Object time_;
    /**
     * <code>required string Time = 6;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string Time = 6;</code>
     */
    public String getTime() {
      Object ref = time_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          time_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Time = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      Object ref = time_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 7;
    private int type_;
    /**
     * <code>required uint32 Type = 7;</code>
     *
     * <pre>
     *报警类型　同于布控类型
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required uint32 Type = 7;</code>
     *
     * <pre>
     *报警类型　同于布控类型
     * </pre>
     */
    public int getType() {
      return type_;
    }

    public static final int PLATELICENSE_FIELD_NUMBER = 8;
    private Object plateLicense_;
    /**
     * <code>optional string PlateLicense = 8;</code>
     */
    public boolean hasPlateLicense() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string PlateLicense = 8;</code>
     */
    public String getPlateLicense() {
      Object ref = plateLicense_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          plateLicense_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string PlateLicense = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPlateLicenseBytes() {
      Object ref = plateLicense_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        plateLicense_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLATECOLOR_FIELD_NUMBER = 9;
    private Object plateColor_;
    /**
     * <code>optional string PlateColor = 9;</code>
     */
    public boolean hasPlateColor() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string PlateColor = 9;</code>
     */
    public String getPlateColor() {
      Object ref = plateColor_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          plateColor_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string PlateColor = 9;</code>
     */
    public com.google.protobuf.ByteString
        getPlateColorBytes() {
      Object ref = plateColor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        plateColor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLATETYPE_FIELD_NUMBER = 10;
    private Object plateType_;
    /**
     * <code>optional string PlateType = 10;</code>
     */
    public boolean hasPlateType() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string PlateType = 10;</code>
     */
    public String getPlateType() {
      Object ref = plateType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          plateType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string PlateType = 10;</code>
     */
    public com.google.protobuf.ByteString
        getPlateTypeBytes() {
      Object ref = plateType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        plateType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VEHICLELOGORECOG_FIELD_NUMBER = 11;
    private Object vehicleLogoRecog_;
    /**
     * <code>optional string VehicleLogoRecog = 11;</code>
     */
    public boolean hasVehicleLogoRecog() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string VehicleLogoRecog = 11;</code>
     */
    public String getVehicleLogoRecog() {
      Object ref = vehicleLogoRecog_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          vehicleLogoRecog_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string VehicleLogoRecog = 11;</code>
     */
    public com.google.protobuf.ByteString
        getVehicleLogoRecogBytes() {
      Object ref = vehicleLogoRecog_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        vehicleLogoRecog_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VEHICLECOLOR_FIELD_NUMBER = 12;
    private Object vehicleColor_;
    /**
     * <code>optional string VehicleColor = 12;</code>
     */
    public boolean hasVehicleColor() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional string VehicleColor = 12;</code>
     */
    public String getVehicleColor() {
      Object ref = vehicleColor_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          vehicleColor_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string VehicleColor = 12;</code>
     */
    public com.google.protobuf.ByteString
        getVehicleColorBytes() {
      Object ref = vehicleColor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        vehicleColor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VEHICLETYPE_FIELD_NUMBER = 13;
    private int vehicleType_;
    /**
     * <code>optional int32 VehicleType = 13;</code>
     */
    public boolean hasVehicleType() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional int32 VehicleType = 13;</code>
     */
    public int getVehicleType() {
      return vehicleType_;
    }

    public static final int VEHICLESPEED_FIELD_NUMBER = 14;
    private float vehicleSpeed_;
    /**
     * <code>optional float VehicleSpeed = 14;</code>
     */
    public boolean hasVehicleSpeed() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional float VehicleSpeed = 14;</code>
     */
    public float getVehicleSpeed() {
      return vehicleSpeed_;
    }

    private void initFields() {
      id_ = "";
      vehicleId_ = "";
      preyInfoId_ = "";
      priority_ = 0;
      deviceId_ = "";
      time_ = "";
      type_ = 0;
      plateLicense_ = "";
      plateColor_ = "";
      plateType_ = "";
      vehicleLogoRecog_ = "";
      vehicleColor_ = "";
      vehicleType_ = 0;
      vehicleSpeed_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVehicleId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPreyInfoId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPriority()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeviceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getVehicleIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPreyInfoIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, priority_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getTimeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt32(7, type_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getPlateLicenseBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getPlateColorBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getPlateTypeBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getVehicleLogoRecogBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getVehicleColorBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(13, vehicleType_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeFloat(14, vehicleSpeed_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getVehicleIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPreyInfoIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, priority_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getTimeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, type_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getPlateLicenseBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getPlateColorBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getPlateTypeBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getVehicleLogoRecogBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getVehicleColorBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, vehicleType_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(14, vehicleSpeed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static AlarmInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AlarmInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AlarmInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AlarmInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AlarmInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static AlarmInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static AlarmInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static AlarmInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static AlarmInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static AlarmInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(AlarmInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.AlarmInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.AlarmInfo)
        AlarmInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AlarmInfoProtos.internal_static_protocol_AlarmInfo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AlarmInfoProtos.internal_static_protocol_AlarmInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AlarmInfo.class, Builder.class);
      }

      // Construct using protocol.AlarmInfoProtos.AlarmInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        vehicleId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        preyInfoId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        priority_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        plateLicense_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        plateColor_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        plateType_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        vehicleLogoRecog_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        vehicleColor_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        vehicleType_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        vehicleSpeed_ = 0F;
        bitField0_ = (bitField0_ & ~0x00002000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AlarmInfoProtos.internal_static_protocol_AlarmInfo_descriptor;
      }

      public AlarmInfo getDefaultInstanceForType() {
        return AlarmInfo.getDefaultInstance();
      }

      public AlarmInfo build() {
        AlarmInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AlarmInfo buildPartial() {
        AlarmInfo result = new AlarmInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.vehicleId_ = vehicleId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.preyInfoId_ = preyInfoId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.priority_ = priority_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.plateLicense_ = plateLicense_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.plateColor_ = plateColor_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.plateType_ = plateType_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.vehicleLogoRecog_ = vehicleLogoRecog_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.vehicleColor_ = vehicleColor_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.vehicleType_ = vehicleType_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.vehicleSpeed_ = vehicleSpeed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AlarmInfo) {
          return mergeFrom((AlarmInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AlarmInfo other) {
        if (other == AlarmInfo.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasVehicleId()) {
          bitField0_ |= 0x00000002;
          vehicleId_ = other.vehicleId_;
          onChanged();
        }
        if (other.hasPreyInfoId()) {
          bitField0_ |= 0x00000004;
          preyInfoId_ = other.preyInfoId_;
          onChanged();
        }
        if (other.hasPriority()) {
          setPriority(other.getPriority());
        }
        if (other.hasDeviceId()) {
          bitField0_ |= 0x00000010;
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.hasTime()) {
          bitField0_ |= 0x00000020;
          time_ = other.time_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasPlateLicense()) {
          bitField0_ |= 0x00000080;
          plateLicense_ = other.plateLicense_;
          onChanged();
        }
        if (other.hasPlateColor()) {
          bitField0_ |= 0x00000100;
          plateColor_ = other.plateColor_;
          onChanged();
        }
        if (other.hasPlateType()) {
          bitField0_ |= 0x00000200;
          plateType_ = other.plateType_;
          onChanged();
        }
        if (other.hasVehicleLogoRecog()) {
          bitField0_ |= 0x00000400;
          vehicleLogoRecog_ = other.vehicleLogoRecog_;
          onChanged();
        }
        if (other.hasVehicleColor()) {
          bitField0_ |= 0x00000800;
          vehicleColor_ = other.vehicleColor_;
          onChanged();
        }
        if (other.hasVehicleType()) {
          setVehicleType(other.getVehicleType());
        }
        if (other.hasVehicleSpeed()) {
          setVehicleSpeed(other.getVehicleSpeed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {

          return false;
        }
        if (!hasVehicleId()) {

          return false;
        }
        if (!hasPreyInfoId()) {

          return false;
        }
        if (!hasPriority()) {

          return false;
        }
        if (!hasDeviceId()) {

          return false;
        }
        if (!hasTime()) {

          return false;
        }
        if (!hasType()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AlarmInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AlarmInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object id_ = "";
      /**
       * <code>required string Id = 1;</code>
       *
       * <pre>
       *报警标号
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string Id = 1;</code>
       *
       * <pre>
       *报警标号
       * </pre>
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string Id = 1;</code>
       *
       * <pre>
       *报警标号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Id = 1;</code>
       *
       * <pre>
       *报警标号
       * </pre>
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Id = 1;</code>
       *
       * <pre>
       *报警标号
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string Id = 1;</code>
       *
       * <pre>
       *报警标号
       * </pre>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private Object vehicleId_ = "";
      /**
       * <code>required string VehicleId = 2;</code>
       *
       * <pre>
       *车辆信息编号
       * </pre>
       */
      public boolean hasVehicleId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string VehicleId = 2;</code>
       *
       * <pre>
       *车辆信息编号
       * </pre>
       */
      public String getVehicleId() {
        Object ref = vehicleId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            vehicleId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string VehicleId = 2;</code>
       *
       * <pre>
       *车辆信息编号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getVehicleIdBytes() {
        Object ref = vehicleId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          vehicleId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string VehicleId = 2;</code>
       *
       * <pre>
       *车辆信息编号
       * </pre>
       */
      public Builder setVehicleId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        vehicleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string VehicleId = 2;</code>
       *
       * <pre>
       *车辆信息编号
       * </pre>
       */
      public Builder clearVehicleId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        vehicleId_ = getDefaultInstance().getVehicleId();
        onChanged();
        return this;
      }
      /**
       * <code>required string VehicleId = 2;</code>
       *
       * <pre>
       *车辆信息编号
       * </pre>
       */
      public Builder setVehicleIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        vehicleId_ = value;
        onChanged();
        return this;
      }

      private Object preyInfoId_ = "";
      /**
       * <code>required string PreyInfoId = 3;</code>
       *
       * <pre>
       * 布控信息编号
       * </pre>
       */
      public boolean hasPreyInfoId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string PreyInfoId = 3;</code>
       *
       * <pre>
       * 布控信息编号
       * </pre>
       */
      public String getPreyInfoId() {
        Object ref = preyInfoId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            preyInfoId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string PreyInfoId = 3;</code>
       *
       * <pre>
       * 布控信息编号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPreyInfoIdBytes() {
        Object ref = preyInfoId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          preyInfoId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string PreyInfoId = 3;</code>
       *
       * <pre>
       * 布控信息编号
       * </pre>
       */
      public Builder setPreyInfoId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        preyInfoId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string PreyInfoId = 3;</code>
       *
       * <pre>
       * 布控信息编号
       * </pre>
       */
      public Builder clearPreyInfoId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        preyInfoId_ = getDefaultInstance().getPreyInfoId();
        onChanged();
        return this;
      }
      /**
       * <code>required string PreyInfoId = 3;</code>
       *
       * <pre>
       * 布控信息编号
       * </pre>
       */
      public Builder setPreyInfoIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        preyInfoId_ = value;
        onChanged();
        return this;
      }

      private int priority_ ;
      /**
       * <code>required uint32 Priority = 4;</code>
       *
       * <pre>
       *报警级别　同于布控级别
       * </pre>
       */
      public boolean hasPriority() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 Priority = 4;</code>
       *
       * <pre>
       *报警级别　同于布控级别
       * </pre>
       */
      public int getPriority() {
        return priority_;
      }
      /**
       * <code>required uint32 Priority = 4;</code>
       *
       * <pre>
       *报警级别　同于布控级别
       * </pre>
       */
      public Builder setPriority(int value) {
        bitField0_ |= 0x00000008;
        priority_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 Priority = 4;</code>
       *
       * <pre>
       *报警级别　同于布控级别
       * </pre>
       */
      public Builder clearPriority() {
        bitField0_ = (bitField0_ & ~0x00000008);
        priority_ = 0;
        onChanged();
        return this;
      }

      private Object deviceId_ = "";
      /**
       * <code>required string DeviceId = 5;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string DeviceId = 5;</code>
       */
      public String getDeviceId() {
        Object ref = deviceId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string DeviceId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string DeviceId = 5;</code>
       */
      public Builder setDeviceId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string DeviceId = 5;</code>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>required string DeviceId = 5;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        deviceId_ = value;
        onChanged();
        return this;
      }

      private Object time_ = "";
      /**
       * <code>required string Time = 6;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string Time = 6;</code>
       */
      public String getTime() {
        Object ref = time_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            time_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string Time = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Time = 6;</code>
       */
      public Builder setTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Time = 6;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string Time = 6;</code>
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        time_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>required uint32 Type = 7;</code>
       *
       * <pre>
       *报警类型　同于布控类型
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required uint32 Type = 7;</code>
       *
       * <pre>
       *报警类型　同于布控类型
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required uint32 Type = 7;</code>
       *
       * <pre>
       *报警类型　同于布控类型
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000040;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 Type = 7;</code>
       *
       * <pre>
       *报警类型　同于布控类型
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        type_ = 0;
        onChanged();
        return this;
      }

      private Object plateLicense_ = "";
      /**
       * <code>optional string PlateLicense = 8;</code>
       */
      public boolean hasPlateLicense() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string PlateLicense = 8;</code>
       */
      public String getPlateLicense() {
        Object ref = plateLicense_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            plateLicense_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string PlateLicense = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPlateLicenseBytes() {
        Object ref = plateLicense_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          plateLicense_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string PlateLicense = 8;</code>
       */
      public Builder setPlateLicense(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        plateLicense_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string PlateLicense = 8;</code>
       */
      public Builder clearPlateLicense() {
        bitField0_ = (bitField0_ & ~0x00000080);
        plateLicense_ = getDefaultInstance().getPlateLicense();
        onChanged();
        return this;
      }
      /**
       * <code>optional string PlateLicense = 8;</code>
       */
      public Builder setPlateLicenseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        plateLicense_ = value;
        onChanged();
        return this;
      }

      private Object plateColor_ = "";
      /**
       * <code>optional string PlateColor = 9;</code>
       */
      public boolean hasPlateColor() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string PlateColor = 9;</code>
       */
      public String getPlateColor() {
        Object ref = plateColor_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            plateColor_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string PlateColor = 9;</code>
       */
      public com.google.protobuf.ByteString
          getPlateColorBytes() {
        Object ref = plateColor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          plateColor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string PlateColor = 9;</code>
       */
      public Builder setPlateColor(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        plateColor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string PlateColor = 9;</code>
       */
      public Builder clearPlateColor() {
        bitField0_ = (bitField0_ & ~0x00000100);
        plateColor_ = getDefaultInstance().getPlateColor();
        onChanged();
        return this;
      }
      /**
       * <code>optional string PlateColor = 9;</code>
       */
      public Builder setPlateColorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        plateColor_ = value;
        onChanged();
        return this;
      }

      private Object plateType_ = "";
      /**
       * <code>optional string PlateType = 10;</code>
       */
      public boolean hasPlateType() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string PlateType = 10;</code>
       */
      public String getPlateType() {
        Object ref = plateType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            plateType_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string PlateType = 10;</code>
       */
      public com.google.protobuf.ByteString
          getPlateTypeBytes() {
        Object ref = plateType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          plateType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string PlateType = 10;</code>
       */
      public Builder setPlateType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        plateType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string PlateType = 10;</code>
       */
      public Builder clearPlateType() {
        bitField0_ = (bitField0_ & ~0x00000200);
        plateType_ = getDefaultInstance().getPlateType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string PlateType = 10;</code>
       */
      public Builder setPlateTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        plateType_ = value;
        onChanged();
        return this;
      }

      private Object vehicleLogoRecog_ = "";
      /**
       * <code>optional string VehicleLogoRecog = 11;</code>
       */
      public boolean hasVehicleLogoRecog() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string VehicleLogoRecog = 11;</code>
       */
      public String getVehicleLogoRecog() {
        Object ref = vehicleLogoRecog_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            vehicleLogoRecog_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string VehicleLogoRecog = 11;</code>
       */
      public com.google.protobuf.ByteString
          getVehicleLogoRecogBytes() {
        Object ref = vehicleLogoRecog_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          vehicleLogoRecog_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string VehicleLogoRecog = 11;</code>
       */
      public Builder setVehicleLogoRecog(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        vehicleLogoRecog_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string VehicleLogoRecog = 11;</code>
       */
      public Builder clearVehicleLogoRecog() {
        bitField0_ = (bitField0_ & ~0x00000400);
        vehicleLogoRecog_ = getDefaultInstance().getVehicleLogoRecog();
        onChanged();
        return this;
      }
      /**
       * <code>optional string VehicleLogoRecog = 11;</code>
       */
      public Builder setVehicleLogoRecogBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        vehicleLogoRecog_ = value;
        onChanged();
        return this;
      }

      private Object vehicleColor_ = "";
      /**
       * <code>optional string VehicleColor = 12;</code>
       */
      public boolean hasVehicleColor() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional string VehicleColor = 12;</code>
       */
      public String getVehicleColor() {
        Object ref = vehicleColor_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            vehicleColor_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string VehicleColor = 12;</code>
       */
      public com.google.protobuf.ByteString
          getVehicleColorBytes() {
        Object ref = vehicleColor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          vehicleColor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string VehicleColor = 12;</code>
       */
      public Builder setVehicleColor(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        vehicleColor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string VehicleColor = 12;</code>
       */
      public Builder clearVehicleColor() {
        bitField0_ = (bitField0_ & ~0x00000800);
        vehicleColor_ = getDefaultInstance().getVehicleColor();
        onChanged();
        return this;
      }
      /**
       * <code>optional string VehicleColor = 12;</code>
       */
      public Builder setVehicleColorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        vehicleColor_ = value;
        onChanged();
        return this;
      }

      private int vehicleType_ ;
      /**
       * <code>optional int32 VehicleType = 13;</code>
       */
      public boolean hasVehicleType() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional int32 VehicleType = 13;</code>
       */
      public int getVehicleType() {
        return vehicleType_;
      }
      /**
       * <code>optional int32 VehicleType = 13;</code>
       */
      public Builder setVehicleType(int value) {
        bitField0_ |= 0x00001000;
        vehicleType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 VehicleType = 13;</code>
       */
      public Builder clearVehicleType() {
        bitField0_ = (bitField0_ & ~0x00001000);
        vehicleType_ = 0;
        onChanged();
        return this;
      }

      private float vehicleSpeed_ ;
      /**
       * <code>optional float VehicleSpeed = 14;</code>
       */
      public boolean hasVehicleSpeed() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional float VehicleSpeed = 14;</code>
       */
      public float getVehicleSpeed() {
        return vehicleSpeed_;
      }
      /**
       * <code>optional float VehicleSpeed = 14;</code>
       */
      public Builder setVehicleSpeed(float value) {
        bitField0_ |= 0x00002000;
        vehicleSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float VehicleSpeed = 14;</code>
       */
      public Builder clearVehicleSpeed() {
        bitField0_ = (bitField0_ & ~0x00002000);
        vehicleSpeed_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol.AlarmInfo)
    }

    static {
      defaultInstance = new AlarmInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol.AlarmInfo)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_AlarmInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_AlarmInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024PATH/AlarmInfo.proto\022\010protocol\"\226\002\n\tAla" +
      "rmInfo\022\n\n\002Id\030\001 \002(\t\022\021\n\tVehicleId\030\002 \002(\t\022\022\n" +
      "\nPreyInfoId\030\003 \002(\t\022\020\n\010Priority\030\004 \002(\r\022\020\n\010D" +
      "eviceId\030\005 \002(\t\022\014\n\004Time\030\006 \002(\t\022\014\n\004Type\030\007 \002(" +
      "\r\022\024\n\014PlateLicense\030\010 \001(\t\022\022\n\nPlateColor\030\t " +
      "\001(\t\022\021\n\tPlateType\030\n \001(\t\022\030\n\020VehicleLogoRec" +
      "og\030\013 \001(\t\022\024\n\014VehicleColor\030\014 \001(\t\022\023\n\013Vehicl" +
      "eType\030\r \001(\005\022\024\n\014VehicleSpeed\030\016 \001(\002B\033\n\010pro" +
      "tocolB\017AlarmInfoProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_AlarmInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_AlarmInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_AlarmInfo_descriptor,
        new String[] { "Id", "VehicleId", "PreyInfoId", "Priority", "DeviceId", "Time", "Type", "PlateLicense", "PlateColor", "PlateType", "VehicleLogoRecog", "VehicleColor", "VehicleType", "VehicleSpeed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
